export enum ACTIONS {
  'GET_MOVIES' = 'GET_MOVIES',
  'SET_TOTAL' = 'SET_TOTAL',
  'SET_GANRE_FILTER' = 'SET_GANRE_FILTER',
  'SET_SORTING' = 'SET_SORTING',
  'SET_MOVIE_ID' = 'SET_MOVIE_ID',
  'GET_MOVIE' = 'GET_MOVIE',
  'ADD_MOVIE' = 'ADD_MOVIE',
  'EDIT_MOVIE' = 'EDIT_MOVIE',
  'DELETE_MOVIE' = 'DELETE_MOVIE',
}

export default ACTIONS;
